# vim: set ft=ansible
---
- name: Set up osquery Apt Repository Key
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  when: item.name is defined
  with_items: "{{ _osquery.deb822_repository | default([]) }}"

- name: Install osquery
  ansible.builtin.apt:
    pkg: osquery
    state: present
    update_cache: true
